# Que es Numpy

- Es un paquete para computo cientifico
- Los utilizamos para crear vectores y matrices (ndarray)
- Podemos hacer calculos matematicos y cientificos
- Es rapido y eficiente

In [1]:
import numpy as np

<b> Creacion de arreglos</b>

In [2]:
# Mediante una lista
numeros_lista = [1, 2, 3, 4, 5, 6]
numeros_array = np.array(numeros_lista)
numeros_array

array([1, 2, 3, 4, 5, 6])

In [3]:
# Inicializamos un arreglo con 0
ceros = np.zeros(10)
ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# Agregamos numeros del 0 al 10
inicio = np.arange(10)
inicio

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# Inica desde 0 =, termina antes del 19 y va a ir de dos en dos
pares = np.arange(0,20, 2)
pares

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [31]:
# Crear arreglos de dos dimensiones
numeros_dos = np.array([[1, 3, 4], [2, 3, 4]])
numeros_dos

array([[1, 3, 4],
       [2, 3, 4]])

In [12]:
# Crear arreglos con tipos de datos definidos
numeros_tres = np.array([23, 5, 4], dtype='int16')
numeros_tres

array([23,  5,  4], dtype=int16)

In [13]:
# Crear arreglo bidimensional con dos filas y cinco columnas
pares.reshape(2 , 5)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

<b> Operaciones con arreglos </b>

In [14]:
# Suma a todos los elemtnos 1
impares = pares + 1
impares

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [15]:
# Suma todos loes slemetnos del arreglo
impares.sum() 

100

In [16]:
# Saca el promedio dek arregki
impares.mean()

10.0

In [17]:
# Saca la varianza del arreglo
impares.var()

33.0

<b> Metodos con arreglos </b>

In [19]:
# Ordenar de menor a mayor un arreglo
notas = np.array([23, 34, 0, 1, 200, 45, 54, 12, 5, 23, 50])
np.sort(notas)
notas

array([ 23,  34,   0,   1, 200,  45,  54,  12,   5,  23,  50])

In [20]:
# Odeerna de mayor a menor
-np.sort(-notas)
notas

array([ 23,  34,   0,   1, 200,  45,  54,  12,   5,  23,  50])

In [21]:
# LLenar todo un arreglo con un mismo numero
cincos = np.full((2,2), 5)
cincos

array([[5, 5],
       [5, 5]])

In [22]:
# LLenar un arreglo de forma ramdon
random = np.random.rand(4,2)
random

array([[0.49804981, 0.89174362],
       [0.10267691, 0.89217448],
       [0.57718735, 0.29054365],
       [0.23807631, 0.03679978]])

<b> Duplicaciones de arreglos</b>
<br>
Cuando asifnamos directamente el arreglo, estamos redirigiendo a esa variable a la misma direccion de memoira
Que tiene el arreglo original
Por tanto cuando cambiamos un elemento del arreglo nuevo tambien fecta al arreglo original

In [23]:
f = np.array([1, 3, 4])
g = f
g[0] = 100
f

array([100,   3,   4])

Cuando usamos el metodo copy, se crea otra direccion de memoria, por tanto no se modificar la copia si el original es afectado



In [25]:
f = np.array([2, 3, 4, 5])
g = f.copy()
g

array([2, 3, 4, 5])

<b> Condicionales </b>

In [27]:
# Retorna lista booleana de quienes cumplen la condcion
arr = np.linspace(1, 10, 10, dtype='int8')
arr < 5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [28]:
# Si hacemos indexing con condiciones solo nso retorn los elementos que cumplan
arr[arr > 5]

array([ 6,  7,  8,  9, 10], dtype=int8)